use std::fs;
use std::io::prelude::*;
use std::io::{self, BufWriter, Write};
use std::path::Path;

use crate::ast::*;

pub struct Compiler<W: Write> {
    scope: usize,
    buf: W,
    for_count: usize
}

impl<W: Write> Compiler<W> {
    pub fn new(buf: W) -> Compiler<W> {
        Compiler { scope: 0, buf, for_count: 0 }
    }

    pub fn compile(&mut self, ast: Expr) -> io::Result<()> {
        // fs::remove_file(&path)?;
        // let mut stream = BufWriter::new(fs::File::create(path)?);
        self.buf.write(b"@echo off\n")?;
        self.buf
            .write(b"REM AUTO-GENERATED FILE. DO NOT MODIFY.\n")?;
        self.buf
            .write(b"REM This file was automatically generated by the ski compiler.\n")?;

        self.compile_expr(ast)?;

        self.buf.write(b"@echo on")?;
        Ok(())
    }

    pub fn compile_func_call(&mut self, ast: Box<FuncCall>) -> io::Result<()> { 
        match ast.func_name.as_str() {
            "range" => self.compile_range(ast.params)?,
            _ => unreachable!()
        }
        Ok(())
    }

    pub fn compile_if(&mut self, i: Box<If>) -> io::Result<()> {
        self.buf.write(b"IF ")?;
        self.compile_expr(i.cond)?;
        self.buf.write(b"( \n")?;
        self.compile_expr(i.then)?;
        self.buf.write(b") \n")?;
        self.buf.write(b"ELSE (")?;
        self.compile_expr(i.else_)?;
        self.buf.write(b")")?;
        Ok(())
    }

    pub fn compile_range(&mut self, mut ast: Vec<Expr>) -> io::Result<()> {
        self.buf.write(b"(")?;
        let p = ast.pop();
        for x in ast {
            self.compile_expr(x)?;
            self.buf.write(b",")?;
        }
        self.compile_expr(p.unwrap())?;
        self.buf.write(b")")?;
        Ok(())
    }
    pub fn compile_expr(&mut self, ast: Expr) -> io::Result<()> {
        match ast {
            Expr::Binary(i) => self.compile_binary_expr(i)?,
            Expr::Variable(i) => write!(self.buf, "%{}%", i)?,
            Expr::Int(i) => write!(self.buf, "{}", i)?,
            Expr::VariableDecl(i) => self.compile_var_decl(i)?,
            Expr::Block(i) => self.compile_block(i)?,
            Expr::For(i) => self.compile_for(i)?,
            Expr::Str(i) =>  write!(self.buf, "{}", i)?,
            Expr::FuncDef(i) => self.compile_func_def(i)?,
            Expr::FuncCall(i) => self.compile_func_call(i)?,
            Expr::Return(i) => self.compile_return(i)?,
            Expr::Break => self.compile_break()?,
            _ => println!("{:?}", ast),
        }
        Ok(())
    }
    pub fn compile_binary_expr(&mut self, ast: Box<BinaryExpr>) -> io::Result<()> {
        self.compile_expr(ast.left)?;
        self.compile_binary_op_kind(ast.op)?;
        self.compile_expr(ast.right)?;
        Ok(())
    }

    pub fn compile_for(&mut self, ast: Box<For>) -> io::Result<()> { 
        self.buf.write(b"FOR /l %%")?;
        self.buf.write(ast.item.as_bytes())?;
        self.buf.write(b" IN ")?;
        self.compile_expr(ast.container)?;
        self.buf.write(b" DO ")?;
        self.compile_expr(ast.body)?;
        Ok(())
    }

    pub fn compile_func_def(&mut self, ast: Box<FuncDef>) -> io::Result<()> {
        self.buf.write(b":")?;
        self.buf.write(ast.name.as_bytes())?;
        self.buf.write(b" ")?;
        if !ast.params.is_empty() {
            self.compile_params(ast.params)?;
        }
        self.buf.write(b"\n")?;
        self.compile_expr(ast.body)?;
        self.buf.write(b"\n")?;
        self.buf.write(b"EXIT /B 0")?;
        Ok(())
    }

    pub fn compile_params(&mut self, mut ast: Vec<String>) -> io::Result<()> { 
        let p = ast.pop();
        for x in ast {
            self.buf.write(x.as_bytes())?;
            self.buf.write(b", ")?;
        }
        let inside = p.unwrap();
        self.buf.write(inside.as_bytes())?;
        Ok(())
    }

    pub fn compile_return(&mut self, ast: Box<Expr>) -> io::Result<()> {
        self.buf.write(b"SET %~1=")?;
        self.compile_expr(*ast)?;
        self.buf.write(b"\nGOTO: EOF")?;
        Ok(())
    }

    pub fn compile_break(&mut self) -> io::Result<()> {
        write!(self.buf, ":ENDFOR{}", self.for_count)?;
        Ok(())
    }
    pub fn compile_var_decl(&mut self, ast: Box<VariableDecl>) -> io::Result<()> {
        self.buf.write(b"SET ")?;
        if ast.is_numeric {
            self.buf.write(b"/A ")?;
        }
       // self.buf.write(b"%")?;
        self.buf.write(ast.name.as_bytes())?;
      //  self.buf.write(b"%")?;
        self.buf.write(b"=")?;
        self.compile_expr(ast.value)?;
        self.buf.write(b"\n")?;
        Ok(())
    }

    pub fn compile_block(&mut self, ast: Vec<Expr>) -> io::Result<()> {
        for x in ast {
            self.compile_expr(x)?;
        }
        Ok(())
    }

    pub fn compile_binary_op_kind(&mut self, ast: BinaryOpKind) -> io::Result<()> {
        self.buf.write(match ast {
            BinaryOpKind::Add => b"+",
            BinaryOpKind::Sub => b"-",
            BinaryOpKind::Mul => b"*",
            BinaryOpKind::Div => b"/",
            BinaryOpKind::Assign => b"=",
            BinaryOpKind::Eq => b"==",
            BinaryOpKind::Ne => b"!=",
            BinaryOpKind::Gt => b">",
            BinaryOpKind::Lt => b"<",
            BinaryOpKind::GtEq => b">=",
            BinaryOpKind::LtEq => b"<=",
            BinaryOpKind::Shr => b">>",
            BinaryOpKind::Shl => b"<<",
            BinaryOpKind::Xor => b"!",
            BinaryOpKind::LogicalAnd => b"&&",
            BinaryOpKind::LogicalOr => b"||",
            BinaryOpKind::BinaryAnd => b"&",
            BinaryOpKind::BinaryOr => b"|",
        })?;
        Ok(())
    }
}
